name: Court
version: 1.1-Beta
main: me.pizza_nachos.bluefire.court.Court
api-version: 1.13
authors: [Pizza_Nachos, Coedster]
description: Plugin Implenting a court system
depend: [Vault]
commands:
    sue:
      description: Sue a player
      usage: /sue <player> <reason> <amount>
    courtvote:
      description: Vote in a court session
      usage: /courtvote <prosecuter/defendent>
    callvote:
      description: Judge calls on the jury to vote
      usage: /callvote
    seeJudges:
      description: prints list of possible judges
      usage: /seeJudges
    courtyes:
      description: Judge decides to hear a case
      usage: /courtyes
    courtno:
      description: Judge decides to not hear a case
      usage: /courtno
    setCourtLocation:
      description: Sets the court location to the location of current judge
      usage: /setCourtLocation
    courtreload:
      description: reloads the config file
    addjudge:
      description: Adds a judge to the list of possible judges
      usage: /addjudge <player name>
